apiVersion: apps/v1
kind: Deployment
metadata:
  name: garak
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garak
  template:
    metadata:
      labels:
        app: garak
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: garak
        image: 825765396079.dkr.ecr.us-east-1.amazonaws.com/garak:77e9358dbd14854595ac48dc290c80b59adfb9a5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: garak-service
  namespace: services
spec:
  selector:
    app: garak
  ports:
  - port: 80
    targetPort: 80
